from sqlmodel import Session, select

from core.models import Dataset, Provenance, Source
from core.schemas import DatasetInput, LanguageInput, LicenseInput, SourceInput
from ingestion.service import IngestionService

_HF = SourceInput(slug="huggingface", name="Hugging Face", base_url="https://huggingface.co")
_KAGGLE = SourceInput(slug="kaggle", name="Kaggle", base_url="https://www.kaggle.com")
_CC_BY = LicenseInput(name="CC BY 4.0", spdx_id="CC-BY-4.0", url="https://creativecommons.org/licenses/by/4.0/")
_MIT = LicenseInput(name="MIT", spdx_id="MIT", url="https://opensource.org/licenses/MIT")


def _count_datasets(session: Session) -> int:
    return len(session.exec(select(Dataset)).all())


def _dataset_exists(session: Session, source_slug: str, external_id: str) -> bool:
    statement = (
        select(Dataset)
        .join(Source)
        .where(Source.slug == source_slug, Dataset.external_id == external_id)
    )
    return session.exec(statement).first() is not None


def _samples() -> list[DatasetInput]:
    return [
        DatasetInput(
            external_id="masakhane/yoruba-asr",
            title="Yoruba ASR Corpus",
            source=_HF,
            language=LanguageInput(code="yor", name="Yoruba", family="Niger-Congo", region="Afrique de l'Ouest"),
            language_raw="Yorùbá",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/yoruba-asr",
            description="Corpus de reconnaissance vocale en yoruba",
            license=_CC_BY,
            data_format="audio",
            size="2.5 GB",
            task_codes=["asr"],
            task_tags_raw="automatic-speech-recognition",
        ),
        DatasetInput(
            external_id="african-nlp/yoruba-text",
            title="Yoruba Text Collection",
            source=_HF,
            language=LanguageInput(code="yor", name="Yoruba", family="Niger-Congo", region="Afrique de l'Ouest"),
            language_raw="yor",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/african-nlp/yoruba-text",
            description="Corpus textuel yoruba",
            license=_MIT,
            data_format="text",
            size="80 MB",
            task_codes=["classification"],
            task_tags_raw="text-classification",
        ),
        DatasetInput(
            external_id="african-voices/wolof-nmt",
            title="Wolof Parallel Corpus",
            source=_HF,
            language=LanguageInput(code="wol", name="Wolof", family="Niger-Congo", region="Afrique de l'Ouest"),
            language_raw="Wolof",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/african-voices/wolof-nmt",
            description="Corpus parallèle wolof-français",
            license=_MIT,
            data_format="text",
            size="120 MB",
            task_codes=["nmt"],
            task_tags_raw="machine-translation",
        ),
        DatasetInput(
            external_id="swahili-news-classification",
            title="Swahili News Classification",
            source=_KAGGLE,
            language=LanguageInput(code="swh", name="Swahili", family="Bantoue", region="Afrique de l'Est"),
            language_raw="swahili",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://www.kaggle.com/datasets/swahili-news-classification",
            description="Articles de presse swahili annotés",
            data_format="text",
            size="45 MB",
            task_codes=["classification"],
            task_tags_raw="text-classification",
        ),
        DatasetInput(
            external_id="masakhane/amharic-asr",
            title="Amharic Speech Recognition",
            source=_HF,
            language=LanguageInput(code="amh", name="Amharique", family="Sémitique", region="Corne de l'Afrique"),
            language_raw="Amharic",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/amharic-asr",
            description="Corpus ASR en amharique (Éthiopie)",
            license=_CC_BY,
            data_format="audio",
            size="1.8 GB",
            task_codes=["asr"],
            task_tags_raw="automatic-speech-recognition",
        ),
        DatasetInput(
            external_id="masakhane/hausa-nmt",
            title="Hausa Machine Translation",
            source=_HF,
            language=LanguageInput(code="hau", name="Haoussa", family="Afro-asiatique", region="Afrique de l'Ouest"),
            language_raw="Hausa",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/hausa-nmt",
            description="Corpus parallèle haoussa-anglais",
            license=_MIT,
            data_format="text",
            size="95 MB",
            task_codes=["nmt"],
            task_tags_raw="machine-translation",
        ),
        DatasetInput(
            external_id="masakhane/igbo-sentiment",
            title="Igbo Sentiment Analysis",
            source=_HF,
            language=LanguageInput(code="ibo", name="Igbo", family="Niger-Congo", region="Afrique de l'Ouest"),
            language_raw="Igbo",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/igbo-sentiment",
            description="Textes igbo annotés pour l'analyse de sentiment",
            license=_CC_BY,
            data_format="text",
            size="12 MB",
            task_codes=["classification"],
            task_tags_raw="sentiment-analysis",
        ),
        DatasetInput(
            external_id="masakhane/zulu-text",
            title="Zulu Text Corpus",
            source=_HF,
            language=LanguageInput(code="zul", name="Zoulou", family="Bantoue", region="Afrique australe"),
            language_raw="isiZulu",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/zulu-text",
            description="Corpus textuel zoulou",
            license=_MIT,
            data_format="text",
            size="55 MB",
            task_codes=["classification"],
            task_tags_raw="text-classification",
        ),
        DatasetInput(
            external_id="masakhane/xhosa-asr",
            title="Xhosa ASR Dataset",
            source=_HF,
            language=LanguageInput(code="xho", name="Xhosa", family="Bantoue", region="Afrique australe"),
            language_raw="isiXhosa",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/xhosa-asr",
            description="Enregistrements vocaux xhosa pour la reconnaissance automatique",
            license=_CC_BY,
            data_format="audio",
            size="900 MB",
            task_codes=["asr"],
            task_tags_raw="automatic-speech-recognition",
        ),
        DatasetInput(
            external_id="masakhane/twi-nmt",
            title="Twi Translation Corpus",
            source=_HF,
            language=LanguageInput(code="twi", name="Twi", family="Niger-Congo", region="Afrique de l'Ouest"),
            language_raw="Twi",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/twi-nmt",
            description="Corpus parallèle twi-anglais (Ghana)",
            license=_MIT,
            data_format="text",
            size="70 MB",
            task_codes=["nmt"],
            task_tags_raw="machine-translation",
        ),
        DatasetInput(
            external_id="african-nlp/fon-text",
            title="Fon Text Resources",
            source=_HF,
            language=LanguageInput(code="fon", name="Fon", family="Niger-Congo", region="Afrique de l'Ouest"),
            language_raw="Fon",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/african-nlp/fon-text",
            description="Ressources textuelles en fon (Bénin)",
            license=_CC_BY,
            data_format="text",
            size="18 MB",
            task_codes=["classification"],
            task_tags_raw="text-classification",
        ),
        DatasetInput(
            external_id="masakhane/bambara-nmt",
            title="Bambara Parallel Texts",
            source=_HF,
            language=LanguageInput(code="bam", name="Bambara", family="Niger-Congo", region="Afrique de l'Ouest"),
            language_raw="Bambara",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/bambara-nmt",
            description="Corpus parallèle bambara-français (Mali)",
            license=_MIT,
            data_format="text",
            size="60 MB",
            task_codes=["nmt"],
            task_tags_raw="machine-translation",
        ),
        DatasetInput(
            external_id="masakhane/lingala-asr",
            title="Lingala Speech Corpus",
            source=_HF,
            language=LanguageInput(code="lin", name="Lingala", family="Bantoue", region="Afrique centrale"),
            language_raw="Lingala",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/lingala-asr",
            description="Corpus vocal lingala (RDC, Congo)",
            license=_CC_BY,
            data_format="audio",
            size="1.2 GB",
            task_codes=["asr"],
            task_tags_raw="automatic-speech-recognition",
        ),
        DatasetInput(
            external_id="masakhane/oromo-text",
            title="Oromo Text Collection",
            source=_HF,
            language=LanguageInput(code="orm", name="Oromo", family="Couchitique", region="Corne de l'Afrique"),
            language_raw="Oromo",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/oromo-text",
            description="Corpus textuel oromo (Éthiopie, Kenya)",
            license=_MIT,
            data_format="text",
            size="40 MB",
            task_codes=["classification"],
            task_tags_raw="text-classification",
        ),
        DatasetInput(
            external_id="masakhane/somali-nmt",
            title="Somali Translation Dataset",
            source=_HF,
            language=LanguageInput(code="som", name="Somali", family="Couchitique", region="Corne de l'Afrique"),
            language_raw="Somali",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/somali-nmt",
            description="Corpus parallèle somali-anglais",
            license=_MIT,
            data_format="text",
            size="85 MB",
            task_codes=["nmt"],
            task_tags_raw="machine-translation",
        ),
        DatasetInput(
            external_id="masakhane/kinyarwanda-sentiment",
            title="Kinyarwanda Sentiment Corpus",
            source=_HF,
            language=LanguageInput(code="kin", name="Kinyarwanda", family="Bantoue", region="Afrique de l'Est"),
            language_raw="Kinyarwanda",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/kinyarwanda-sentiment",
            description="Analyse de sentiment en kinyarwanda (Rwanda)",
            license=_CC_BY,
            data_format="text",
            size="22 MB",
            task_codes=["classification"],
            task_tags_raw="sentiment-analysis",
        ),
        DatasetInput(
            external_id="masakhane/fulfulde-text",
            title="Fulfulde Text Corpus",
            source=_HF,
            language=LanguageInput(code="ful", name="Peul", family="Niger-Congo", region="Afrique de l'Ouest"),
            language_raw="Fulfulde",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/fulfulde-text",
            description="Corpus textuel peul (fulfulde)",
            license=_MIT,
            data_format="text",
            size="35 MB",
            task_codes=["classification"],
            task_tags_raw="text-classification",
        ),
        DatasetInput(
            external_id="masakhane/ewe-asr",
            title="Ewe Speech Recognition",
            source=_HF,
            language=LanguageInput(code="ewe", name="Éwé", family="Niger-Congo", region="Afrique de l'Ouest"),
            language_raw="Ewe",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/ewe-asr",
            description="Corpus ASR en éwé (Ghana, Togo)",
            license=_CC_BY,
            data_format="audio",
            size="650 MB",
            task_codes=["asr"],
            task_tags_raw="automatic-speech-recognition",
        ),
        DatasetInput(
            external_id="masakhane/malagasy-nmt",
            title="Malagasy Translation Corpus",
            source=_HF,
            language=LanguageInput(code="mlg", name="Malgache", family="Austronésien", region="Océan Indien"),
            language_raw="Malagasy",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/malagasy-nmt",
            description="Corpus parallèle malgache-français (Madagascar)",
            license=_MIT,
            data_format="text",
            size="50 MB",
            task_codes=["nmt"],
            task_tags_raw="machine-translation",
        ),
        DatasetInput(
            external_id="masakhane/shona-text",
            title="Shona Text Dataset",
            source=_HF,
            language=LanguageInput(code="sna", name="Shona", family="Bantoue", region="Afrique australe"),
            language_raw="Shona",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/shona-text",
            description="Corpus textuel shona (Zimbabwe)",
            license=_CC_BY,
            data_format="text",
            size="28 MB",
            task_codes=["classification"],
            task_tags_raw="text-classification",
        ),
        DatasetInput(
            external_id="masakhane/tigrinya-asr",
            title="Tigrinya ASR Corpus",
            source=_HF,
            language=LanguageInput(code="tir", name="Tigrigna", family="Sémitique", region="Corne de l'Afrique"),
            language_raw="Tigrinya",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/tigrinya-asr",
            description="Reconnaissance vocale en tigrigna (Érythrée, Éthiopie)",
            license=_CC_BY,
            data_format="audio",
            size="780 MB",
            task_codes=["asr"],
            task_tags_raw="automatic-speech-recognition",
        ),
        DatasetInput(
            external_id="masakhane/luganda-nmt",
            title="Luganda Parallel Corpus",
            source=_HF,
            language=LanguageInput(code="lug", name="Luganda", family="Bantoue", region="Afrique de l'Est"),
            language_raw="Luganda",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/luganda-nmt",
            description="Corpus parallèle luganda-anglais (Ouganda)",
            license=_MIT,
            data_format="text",
            size="42 MB",
            task_codes=["nmt"],
            task_tags_raw="machine-translation",
        ),
        DatasetInput(
            external_id="masakhane/tamazight-text",
            title="Tamazight Text Resources",
            source=_HF,
            language=LanguageInput(code="ber", name="Tamazight", family="Berbère", region="Afrique du Nord"),
            language_raw="Tamazight",
            provenance=Provenance.SYNCHRONISE,
            source_url="https://huggingface.co/datasets/masakhane/tamazight-text",
            description="Ressources textuelles en tamazight (Amazigh)",
            license=_CC_BY,
            data_format="text",
            size="15 MB",
            task_codes=["classification"],
            task_tags_raw="text-classification",
        ),
    ]


def seed_catalog(session: Session) -> int:
    """Synchronise le jeu de datasets de démonstration (idempotent par source + external_id)."""
    service = IngestionService(session)
    created = 0
    for payload in _samples():
        existed = _dataset_exists(session, payload.source.slug, payload.external_id)
        service.persist_dataset(payload)
        if not existed:
            created += 1
    return created


def seed_catalog_if_empty(session: Session) -> int:
    if _count_datasets(session) > 0:
        return 0
    return seed_catalog(session)
